### PR TITLE
Remove restriction that tags must be in Open Tracing ext/tags.ts set

### PR DESCRIPTION
**Pull request by Moocar**
Addresses #67

### CODE REVIEW

**Comment by Moocar** [comment]
I just remembered to actually run the tests. @DanielMSchmidt I'm a bit of a newbie to js. I can't figure out why my new test is failing. `BinaryAnnotation` seems to have a similar signature to `ServerAddr` like in the above tests, but seems to be failing because it isn't a constructor. My gut tells me it's a misunderstanding on my part with how jasmine works. Any ideas?

**Comment by KyleAMathews** [comment]
What happens if you just remove the `new`? `new` is very inconsistently used on JavaScript 🤷‍♂️

**Comment by DanielMSchmidt** [comment]
@Moocar I will look into it tonight, I am sorry I haven't had time earlier 🙈

**Comment by DanielMSchmidt** [comment]
The problem is that the Annotation is missing in the mock of Zipkin we are using for the unit tests.

You need to change the following at `__mocks__/zipkin.js`

```diff
module.exports = {
  Annotation: {
+   BinaryAnnotation: jest.fn(),
    ClientAddr: jest.fn(),
    ClientRecv: jest.fn(),
    ClientSend: jest.fn(),
    ServerAddr: jest.fn(),
    ServerRecv: jest.fn(),
```

Thank you so much for taking the time to build up this PR.

**Comment by Moocar** [comment]
Thanks @DanielMSchmidt . I added the new mock and the tests are passing again.

**Comment by Moocar** [comment]
Looks like `publish-website.sh` wasn't executable which was causing travis to fail. I fixed it :)

**Comment by DanielMSchmidt** [comment]
Published in [1.6.0](https://github.com/DanielMSchmidt/zipkin-javascript-opentracing/releases/tag/v1.6.0)

**Comment by DanielMSchmidt** [comment]
Thank you so much for your help <3

**Comment by Moocar** [comment]
Thanks for the library!

**Pull request merged**
